/**
 * All auth specific paths are autogenerated here
 * documentation: https://better-auth-ui.com/integrations/next-js
 */

import { AuthView } from "@daveyplate/better-auth-ui"
import { authViewPaths } from "@daveyplate/better-auth-ui/server"

export const dynamicParams = false

export function generateStaticParams() {
  return Object.values(authViewPaths).map((path) => ({ path }))
}

export default async function AuthPage({ params }: { params: Promise<{ path: string }> }) {
    const { path } = await params
    
    return (
        <main className="container mx-auto flex grow flex-col items-center justify-center self-center p-4 md:p-6">
            <h4 className="text-3xl text-slate-700 py-8">Admin Portal</h4>
            <AuthView path={path} />
        </main>
    )
}